let x = 2
try {
    x.toPrecision(500)
}
catch(err){
    console.log("Error: ",err)
}